<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SRHPasswordManager_tests.TestNotebook-20240123141406" tests="3" file="SRHPasswordManager_tests.py" time="0.004" timestamp="2024-01-23T14:14:06" failures="0" errors="1" skipped="0">
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_existing" time="0.000" timestamp="2024-01-23T14:14:06"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_not_existing" time="0.000" timestamp="2024-01-23T14:14:06"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_add_entry" time="0.004" timestamp="2024-01-23T14:14:06">
		<error type="EOFError" message="EOF when reading a line"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "c:\users\acer\documents\github\srhpasswordmanager\src\unittest\python\SRHPasswordManager_tests.py", line 24, in test_add_entry
    self.notebook.mock_notebook()
    ^^^^^^^^^^^^^^^^^
  File "c:\users\acer\documents\github\srhpasswordmanager\src\main\python\SRHPasswordManager.py", line 225, in mock_notebook
    nb1.encrypt_and_write(nb1.generate_key())
    ^^^^^^^^^^^^^^^^^
  File "c:\users\acer\documents\github\srhpasswordmanager\src\main\python\SRHPasswordManager.py", line 134, in generate_key
    password = input('Please enter the master password\n')
    ^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line
]]></error>
	</testcase>
</testsuite>
